### ISSUE TITLE
Module build failed: Error: Plugin 0 specified in "base" provided an invalid property of "name"

### ISSUE THREAD

**Issue by legend80s** [Riokai/babel-plugin-transform-remove-console#2]
When built with babel-loader 6.2.4 ("babel-cli": "6.10.1", "babel-core": "6.8.0",), webpack 1.13.2, webpack-dev-server 1.15.1 and webpack.config.js loaders:
```javascript
{
  test: /\.js$/,
  exclude: /\/node_modules\//,
  loader: 'babel-loader',
  query: {
    plugins: [
      'transform-remove-console-enhance',
    ],
  },
}
```
an error occured as:
> Module build failed: Error: Plugin 0 specified in "base" provided an invalid property of "name"
    at Plugin.init (/Users/legend80s/workspace/opensearch-console/node_modules/babel-core/lib/transformation/plugin.js:146:13)

It works after I remove the line [name: "transform-remove-console-enhance"](https://github.com/Riokai/babel-plugin-transform-remove-console/blob/master/src/index.js#L7)

_My solution: update babel-core to it's latest 6.25.0._

This issue can be closed. It is recored here only for the reason that people with the same problem as me but found not solution after googling.

**Comment by Riokai** [comment]
Thanks.
